### ISSUE TITLE
`ccAddresses` is defined as mandatory

### ISSUE THREAD

**Issue by shareefm0** [praveendran-tech/ilimDeliveryServ#2]
In `com.github.ilim.backend.ilimEmailDeliveryServ.model.EmailRequest` there is this code:

```Java
   @NotEmpty(message = "CC addresses must contain valid emails")
    private List<@Email(message = "Each CC address should be a valid email") String> ccAddresses; // List of CC addresses (optional)
```

I missed this in my code review. The `ccAddresses` field is annotated with `@NotEmpty`, which requires it to be non-null and not empty. But as the comment right after it says, this field should be optional. Otherwise, ilim-backend will not be able to send an email to a single receiver.

**Comment by praveendran-tech** [comment]
Fixed this issue
